// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "yanqiaoyu",
            "url": "https://github.com/yanqiaoyu/yToolsBox/tree/poc-master",
            "email": "yqy1160058763@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/settings/values": {
            "get": {
                "description": "模拟SonarQube未授权访问, 这里的路径不能加/api/auth这个前缀",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟SonarQube未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/AuthInURL": {
            "get": {
                "description": "模拟鉴权信息在url中",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟鉴权信息在url中",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径中存在鉴权信息,例如sessionid=1",
                        "name": "sessionid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/DataAmountCanBeModified": {
            "get": {
                "description": "模拟敏感接口返回数据量可修改, 例如path中存在 query=1\u0026pagenum=1\u0026pagesize=10",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟敏感接口返回数据量可修改",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "query是一个可修改的参数, 例如query=1",
                        "name": "query",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "pagenum是一个可修改的参数, 例如pagenum=1",
                        "name": "pagenum",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "pagesize是一个可修改的参数, 例如pagesize=1",
                        "name": "pagesize",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/DeleteInGet": {
            "get": {
                "description": "模拟 GET方式执行危险操作",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟 GET方式执行危险操作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径中存在delete参数,例如delete=1",
                        "name": "delete",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/DifferentDesensePolicy": {
            "get": {
                "description": "模拟脱敏策略不一致, 例如返回2种不同类型的脱敏数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟脱敏策略不一致",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/NoneSensitiveAPINotSec": {
            "post": {
                "description": "模拟非敏感接口未鉴权,请求中不要带鉴权信息即可",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟非敏感接口未鉴权",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/PswdInCookie": {
            "get": {
                "description": "模拟cookie中存在密码信息,这个接口需要请求头中携带cookie这个字段,并且其中含有密码信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟cookie中存在密码信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cookie中填写明文的密码信息,例如Cookie: expires=Thu, 01 Jan 1970 00:00:00 GMT; password=qwert",
                        "name": "cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/PswdInPlainText": {
            "post": {
                "description": "模拟请求数据存在明文密码信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟请求数据存在明文密码信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query中填写明文的密码信息,例如password=123456",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/PswdInPlainTextResp": {
            "get": {
                "description": "模拟响应数据存在密码信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟响应数据存在密码信息",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/PswdInResp": {
            "get": {
                "description": "模拟响应数据存在密码信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟响应数据存在密码信息",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/PswdInURL": {
            "get": {
                "description": "模拟url中存在密码信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟url中存在密码信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "填写明文的密码信息",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/SensitiveAPINotSec": {
            "post": {
                "description": "模拟敏感接口未鉴权,请求中不要带鉴权信息即可",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟敏感接口未鉴权",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/SensitiveDataInURL": {
            "get": {
                "description": "模拟敏感信息在url中",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟敏感信息在url中",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径中存在敏感信息,例如phone=13687148956",
                        "name": "phone",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/TooMuchDataInSingleRequest": {
            "get": {
                "description": "模拟单次访问数据量过大, 例如返回200个姓名",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟单次访问数据量过大",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/TooMuchTypeInSingleRequest": {
            "get": {
                "description": "模拟单次访问敏感类型过多, 例如返回15种类型的敏感数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟单次访问敏感类型过多",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/WeakPasswd": {
            "post": {
                "description": "模拟登录弱密码 或 存在空密码/空密钥问题 或 万能密码注入",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟登录弱密码 或 存在空密码/空密钥问题",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query中填写明文的密码信息,例如password=123456",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "query中填写明文的账号信息,name=admin",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/ws/v1/cluster/apps/new-application": {
            "post": {
                "description": "模拟Hadoop未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟Hadoop未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/fileDownload": {
            "post": {
                "description": "模拟ssh secret key信息泄露",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟ssh secret key信息泄露",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/nacos/v1/auth/users": {
            "post": {
                "description": "模拟Alibaba Nacos未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟Alibaba Nacos未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/xxl-conf-admin/conf/find": {
            "post": {
                "description": "模拟JDBC连接字符串信息泄露",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟JDBC连接字符串信息泄露",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/": {
            "get": {
                "description": "模拟凭证长期生效",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟凭证长期生效",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/baizhi/_search/": {
            "get": {
                "description": "ElasticSearch查询数据接口未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "ElasticSearch查询数据接口未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/_nodes": {
            "get": {
                "description": "ElasticSearch节点目录未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "ElasticSearch节点目录未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/actuator/info": {
            "get": {
                "description": "SpringBoot部分常见路径未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "SpringBoot部分常见路径未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/jolokia/list": {
            "get": {
                "description": "Jolokia未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Jolokia未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/api/webservices/list": {
            "get": {
                "description": "SonarQube未授权访问应用列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "SonarQube未授权访问应用列表",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/v2/api-docs": {
            "get": {
                "description": "Swagger未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Swagger未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/solr/admin/info/system": {
            "get": {
                "description": "Solr未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Solr未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/GetDefualtOssInfo": {
            "get": {
                "description": "云主机Accesskey或Secret key泄漏",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "云主机Accesskey或Secret key泄漏",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/api/v1/namespaces/pods": {
            "get": {
                "description": "Kubernetes API Server未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Kubernetes API Server未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/api/v1/settings/pinner": {
            "get": {
                "description": "Kubernetes Dashboard面板未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Kubernetes Dashboard面板未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        
        },
        "/graphql": {
            "post": {
                "description": "GraphQL未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "GraphQL未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/sendmessage": {
            "post": {
                "description": "短信验证码出现在响应包中",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "短信验证码出现在响应包中",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/ws_utc/resources/setting/keystore": {
            "post": {
                "description": "Weblogic 未授权访问漏洞",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Weblogic 未授权访问漏洞",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },        
        "/apisix/admin/migrate/export": {
            "get": {
                "description": "Apache APISIX Dashboard 认证绕过（CVE-2021-45232）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Apache APISIX Dashboard 认证绕过（CVE-2021-45232）",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },        
        "/dashboardUser": {
            "get": {
                "description": "Apache ShenYu Admin 身份验证绕过漏洞（CVE-2021-37580）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Apache ShenYu Admin 身份验证绕过漏洞（CVE-2021-37580）",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },        
        "/php/login.php": {
            "get": {
                "description": "Cookie没有添加HttpOnly属性",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Cookie没有添加HttpOnly属性",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },           
        "/api/islogin": {
            "get": {
                "description": "JWT认证错误地使用了空加密算法",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "JWT认证错误地使用了空加密算法",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/api/user": {
            "delete": {
                "description": "危险方法未被禁用",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "危险方法未被禁用",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/authenticationserverservlet": {
            "get": {
                "description": "MessageSolution 企业邮件归档管理系统 EEA 存在信息泄露漏洞",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "MessageSolution 企业邮件归档管理系统 EEA 存在信息泄露漏洞",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/WebReport/ReportServer": {
            "get": {
                "description": "FineReport管理平台privilege.xml文件信息泄露",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "FineReport管理平台privilege.xml文件信息泄露",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/a.php": {
            "get": {
                "description": "Tomcat tomcat-users.xml, Apache Axis axis2.xml, Glassfish domain.xml, Jenkins config.xml, Zimbra conf/localconfig.xml信息泄露",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Tomcat tomcat-users.xml, Apache Axis axis2.xml, Glassfish domain.xml, Jenkins config.xml, Zimbra conf/localconfig.xml信息泄露",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/tmui/login.jsp/..;/tmui/locallb/workspace/a.php": {
            "get": {
                "description": "F5 BIG-IP 认证绕过（CVE-2020-5902）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "F5 BIG-IP 认证绕过（CVE-2020-5902）",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/mgmt/tm/util/bash": {
            "post": {
                "description": "F5 BIG-IP 认证绕过（CVE-2022-1388）, F5 BIG-IP命令注入漏洞（CVE-2021-22986）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "F5 BIG-IP 认证绕过（CVE-2022-1388）, F5 BIG-IP命令注入漏洞（CVE-2021-22986）",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/webapi/v1/system/accountmanage/account": {
            "get": {
                "description": "绿盟UTS综合威胁探针信息泄露",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "绿盟UTS综合威胁探针信息泄露",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/_users/org.couchdb.user:vulhub": {
            "put": {
                "description": "Couchdb垂直权限绕过露",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Couchdb垂直权限绕过露",
                "responses": {
                    "201": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/run": {
            "post": {
                "description": "XXL-Job远程命令执行漏洞",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "XXL-Job远程命令执行漏洞",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/actuator/gateway/routes/hacktest": {
            "post": {
                "description": "Spring Cloud Gateway代码注入漏洞（CVE-2022-22947）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Spring Cloud Gateway代码注入漏洞（CVE-2022-22947）",
                "responses": {
                    "201": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/api/project/up": {
            "get": {
                "description": "YApi未授权代码执行",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "YApi未授权代码执行",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/mailsms/s": {
            "get": {
                "description": "Coremail未授权访问（CNVD-2019-78549）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Coremail未授权访问（CNVD-2019-78549）",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/druid/sql.json": {
            "post": {
                "description": "Druid敏感信息泄露",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Druid敏感信息泄露",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/rest/api/latest/groupuserpicker": {
            "get": {
                "description": "Atlassian jira信息泄露漏洞(CVE-2019-8449)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Atlassian jira信息泄露漏洞(CVE-2019-8449)",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/v1/submissions/create": {
            "post": {
                "description": "spark未授权命令执行漏洞",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "spark未授权命令执行漏洞",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/customers/1": {
            "patch": {
                "description": "spring data rest 远程命令执行（CVE-2017-8046）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "spring data rest 远程命令执行（CVE-2017-8046）",
                "responses": {
                    "400": {
                        "description": "返回失败",
                        "schema": {
                            "$ref": "#/definitions/dto.FailResponseMeta"
                        }
                    }
                }
            }
        },
        "/apisix/batch-requests": {
            "post": {
                "description": "Apache APISIX 远程代码执行漏洞（CVE-2022-24112）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Apache APISIX 远程代码执行漏洞（CVE-2022-24112）",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.FailResponseMeta"
                        }
                    }
                }
            }
        },
        "/kylin/api/cubes/kylin_streaming_cube/learn_kylin/migrate": {
            "put": {
                "description": "kylin远程命令执行漏洞（CVE-2020-1956）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "kylin远程命令执行漏洞（CVE-2020-1956）",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.FailResponseMeta"
                        }
                    }
                }
            }
        },
        "/api/v1/secret/kube-system/kubernetes-dashboard-certs": {
            "get": {
                "description": "k8s Dashboard面板认证绕过漏洞（CVE-2018-18264）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "k8s Dashboard面板认证绕过漏洞（CVE-2018-18264）",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.FailResponseMeta"
                        }
                    }
                }
            } 
        },
        "/DbAdminWSService/DbAdminWS": {
            "post": {
                "description": "Cisco Data Center Network Manager 认证绕过漏洞（CVE-2019-15977）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Cisco Data Center Network Manager 认证绕过漏洞（CVE-2019-15977）",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.FailResponseMeta"
                        }
                    }
                }
            } 
        },
        "/service/soap": {
            "post": {
                "description": "Zimbra 组件漏洞信息泄露",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "Zimbra 组件漏洞信息泄露",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.FailResponseMeta"
                        }
                    }
                }
            } 
        },
        "/openapi.json": {
            "get": {
                "description": "API接口文档未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "API接口文档未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.FailResponseMeta"
                        }
                    }
                }
            } 
        },
        "/user": {
            "get": {
                "description": "HTTP Basic Authorization弱口令",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "HTTP Basic Authorization弱口令",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.FailResponseMeta"
                        }
                    }
                }
            } 
        },
        "/user/admin/infolog.log": {
            "get": {
                "description": "重要接口未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "重要接口未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.FailResponseMeta"
                        }
                    }
                }
            } 
        }
    },
    "definitions": { 
        "dto.SuccessResponseMeta": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.2.12",
	Host:             "",
	BasePath:         "/api/auth",
	Schemes:          []string{},
	Title:            "POC工具盒",
	Description:      "用于数据安全POC测试的工具盒",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
