// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "yanqiaoyu",
            "url": "https://github.com/yanqiaoyu/yToolsBox/tree/poc-master",
            "email": "yqy1160058763@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/settings/values": {
            "get": {
                "description": "模拟SonarQube未授权访问, 这里的路径不能加/api/auth这个前缀",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟SonarQube未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/AuthInURL": {
            "get": {
                "description": "模拟鉴权信息在url中",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟鉴权信息在url中",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径中存在鉴权信息,例如sessionid=1",
                        "name": "sessionid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/DataAmountCanBeModified": {
            "get": {
                "description": "模拟敏感接口返回数据量可修改, 例如path中存在 query=1\u0026pagenum=1\u0026pagesize=10",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟敏感接口返回数据量可修改",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "query是一个可修改的参数, 例如query=1",
                        "name": "query",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "pagenum是一个可修改的参数, 例如pagenum=1",
                        "name": "pagenum",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "pagesize是一个可修改的参数, 例如pagesize=1",
                        "name": "pagesize",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/DeleteInGet": {
            "get": {
                "description": "模拟 GET方式执行危险操作",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟 GET方式执行危险操作",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径中存在delete参数,例如delete=1",
                        "name": "delete",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/DifferentDesensePolicy": {
            "get": {
                "description": "模拟脱敏策略不一致, 例如返回2种不同类型的脱敏数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟脱敏策略不一致",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/NoneSensitiveAPINotSec": {
            "post": {
                "description": "模拟非敏感接口未鉴权,请求中不要带鉴权信息即可",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟非敏感接口未鉴权",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/PswdInCookie": {
            "get": {
                "description": "模拟cookie中存在密码信息,这个接口需要请求头中携带cookie这个字段,并且其中含有密码信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟cookie中存在密码信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cookie中填写明文的密码信息,例如Cookie: expires=Thu, 01 Jan 1970 00:00:00 GMT; password=qwert",
                        "name": "cookie",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/PswdInPlainText": {
            "post": {
                "description": "模拟请求数据存在明文密码信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟请求数据存在明文密码信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query中填写明文的密码信息,例如password=123456",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/PswdInPlainTextResp": {
            "get": {
                "description": "模拟响应数据存在密码信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟响应数据存在密码信息",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/PswdInResp": {
            "get": {
                "description": "模拟响应数据存在密码信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟响应数据存在密码信息",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/PswdInURL": {
            "get": {
                "description": "模拟url中存在密码信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟url中存在密码信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "填写明文的密码信息",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/SensitiveAPINotSec": {
            "post": {
                "description": "模拟敏感接口未鉴权,请求中不要带鉴权信息即可",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟敏感接口未鉴权",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/SensitiveDataInURL": {
            "get": {
                "description": "模拟敏感信息在url中",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟敏感信息在url中",
                "parameters": [
                    {
                        "type": "string",
                        "description": "路径中存在敏感信息,例如phone=13687148956",
                        "name": "phone",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/TooMuchDataInSingleRequest": {
            "get": {
                "description": "模拟单次访问数据量过大, 例如返回200个姓名",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟单次访问数据量过大",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/TooMuchTypeInSingleRequest": {
            "get": {
                "description": "模拟单次访问敏感类型过多, 例如返回15种类型的敏感数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟单次访问敏感类型过多",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/WeakPasswd": {
            "post": {
                "description": "模拟登录弱密码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟登录弱密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "query中填写明文的密码信息,例如password=123456",
                        "name": "password",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "query中填写明文的账号信息,name=admin",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/custom/mock/vulnerability/ws/v1/cluster/apps/new-application": {
            "post": {
                "description": "模拟Hadoop未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟Hadoop未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/fileDownload": {
            "post": {
                "description": "模拟ssh secret key信息泄露",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟ssh secret key信息泄露",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/nacos/v1/auth/users": {
            "post": {
                "description": "模拟Alibaba Nacos未授权访问",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟Alibaba Nacos未授权访问",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        },
        "/xxl-conf-admin/conf/find": {
            "post": {
                "description": "模拟JDBC连接字符串信息泄露",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "模拟脆弱性相关的接口"
                ],
                "summary": "模拟JDBC连接字符串信息泄露",
                "responses": {
                    "200": {
                        "description": "返回成功",
                        "schema": {
                            "$ref": "#/definitions/dto.SuccessResponseMeta"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.SuccessResponseMeta": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.2.12",
	Host:             "",
	BasePath:         "/api/auth",
	Schemes:          []string{},
	Title:            "POC工具盒",
	Description:      "用于数据安全POC测试的工具盒",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
