package cons

var HttpSourceSchemaStr = `{
    "name":"http_log",
    "type":"record",
    "fields":[
        {"name":"v","type":"int"},
        {"name":"tenant","type":"string"},
        {"name":"customer","type":"string"},
        {"name":"recordTimestamp","type":"long"},
        {"name":"uploadTimestamp","type":"long"},
        {"name":"insertTimestamp","type":"long"},
        {"name":"recordTime","type":"string"},
        {"name":"uploadTime","type":"string"},
        {"name":"vendor","type":"string"},
        {"name":"productType","type":"string"},
        {"name":"productVer","type":"string"},
        {"name":"manage","type":"string"},
        {"name":"originProductType","type":"string"},
        {"name":"originProductVer","type":"string"},
        {"name":"deviceId","type":"string"},
        {"name":"uuId","type":"string"},
        {"name":"sessionId","type":"string"},
        {"name":"httpId","type":"string"},
        {"name":"srcIp","type":"string"},
        {"name":"srcPort","type":"int"},
        {"name":"srcMac","type":"string"},
        {"name":"srcIpTag","type":"int"},
        {"name":"srcType","type":"int"},
        {"name":"srcSubType","type":"int"},
        {"name":"srcCountry","type":"string"},
        {"name":"srcProvince","type":"string"},
        {"name":"srcCity","type":"string"},
        {"name":"dstIp","type":"string"},
        {"name":"dstPort","type":"int"},
        {"name":"dstMac","type":"string"},
        {"name":"dstIpTag","type":"int"},
        {"name":"dstType","type":"int"},
        {"name":"dstSubType","type":"int"},
        {"name":"dstCountry","type":"string"},
        {"name":"dstProvince","type":"string"},
        {"name":"dstCity","type":"string"},
        {"name":"reqMethod","type":"string"},
        {"name":"uri","type":"string"},
        {"name":"url","type":"string"},
        {"name":"respStatus","type":"int"},
        {"name":"userAgent","type":"string"},
        {"name":"xForwardedFor","type":"string"},
        {"name":"reqContentType","type":"string"},
        {"name":"respContentType","type":"string"},
        {"name":"respServer","type":"string"},
        {"name":"duration","type":"int"},
        {"name":"requestHead","type":"string"},
        {"name":"responseHead","type":"string"},
        {"name":"requestBody","type":"string"},
        {"name":"responseBody","type":"string"},
        {"name":"hostIp","type":"string"},
        {"name":"hostIpValid","type":"string"},
        {"name":"moduleType","type":"string"},
        {"name":"logType","type":"string"},
        {"name":"manageIp","type":["null","string"],"default":null},
        {"name":"deviceIp","type":["null","string"],"default":null},
        {"name":"logSampled","type":["null","int"],"default":null},
        {"name":"logTraceInfo","type":["null","string"],"default":null},
        {"name":"urlHash","type":["null","long"],"default":null},
        {"name":"encryptType","type":["null","int"],"default":null},
        {"name":"encPayloadType","type":["null","int"],"default":null},
        {"name":"encReqType","type":["null","int"],"default":null},
        {"name":"encRspType","type":["null","int"],"default":null},
        {"name":"srcAssetId","type":["null","string"],"default":null},
        {"name":"dstAssetId","type":["null","string"],"default":null},
        {"name":"cloudTs","type":["null","long"],"default":null},
        {"name":"srcRegionId","type":["null","string"],"default":null},
        {"name":"dstRegionId","type":["null","string"],"default":null},
        {"name":"extensions","type":["null","string"],"default":null},
        {"name":"xForwardedForTag","type":["null","int"],"default":null},
        {"name":"reqBodyLen","type":["null","int"],"default":null},
        {"name":"respBodyLen","type":["null","int"],"default":null},
        {"name":"greSrcIp","type":{"type":"array","items":"string"},"default":[]},
        {"name":"greDstIp","type":{"type":"array","items":"string"},"default":[]},
        {"name":"vxlanId","type":{"type":"array","items":"int"},"default":[]},
        {"name":"vlanId","type":{"type":"array","items":"int"},"default":[]},
        {"name":"mplsLabel","type":{"type":"array","items":"int"},"default":[]},
        {"name":"tunnelProtocol","type":{"type":"array","items":"string"},"default":[]},
        {"name":"rawMsg","type":["null","string"],"default":null},
        {"name":"host","type":["null","string"],"default":null},
        {"name":"devUId","type":["null","int"],"default":null},
        {"name":"reqDataGrade","type":["null","int"],"default":null},
        {"name":"reqDataClassifications","type":{"type":"array","items":"string"},"default":[]},
        {"name":"reqDataLabelIds","type":{"type":"array","items":"string"},"default":[]},
        {"name":"reqDataCounts","type":{"type":"array","items":"int"},"default":[]},
        {"name":"reqDataValues","type":["null","string"],"default":null},
        {"name":"respDataGrade","type":["null","int"],"default":null},
        {"name":"respDataClassifications","type":{"type":"array","items":"string"},"default":[]},
        {"name":"respDataLabelIds","type":{"type":"array","items":"string"},"default":[]},
        {"name":"respDataCounts","type":{"type":"array","items":"int"},"default":[]},
        {"name":"respDataValues","type":["null","string"],"default":null},
        {"name":"apiId","type":["null","string"],"default":null},
        {"name":"apiName","type":["null","string"],"default":null},
        {"name":"apiTags","type":{"type":"array","items":"int"},"default":[]},
        {"name":"accountId","type":["null","string"],"default":null},
        {"name":"accountName","type":["null","string"],"default":null},
        {"name":"accountProofId","type":["null","string"],"default":null},
        {"name":"xAppId","type":["null","string"],"default":null},
        {"name":"xAppName","type":["null","string"],"default":null},
        {"name":"xAppGroup","type":["null","string"],"default":null},
        {"name":"xAppTags","type":{"type":"array","items":"string"},"default":[]},
        {"name":"xUserId","type":["null","string"],"default":null},
        {"name":"xUserName","type":["null","string"],"default":null},
        {"name":"xUserDomain","type":["null","string"],"default":null},
        {"name":"xUserGroup","type":["null","string"],"default":null},
        {"name":"xUserGroupId","type":["null","string"],"default":null},
        {"name":"xUserSource","type":["null","string"],"default":null},
        {"name":"xUserRoles","type":{"type":"array","items":"string"},"default":[]},
        {"name":"xUserTags","type":{"type":"array","items":"string"},"default":[]},
        {"name":"xUserProofId","type":["null","string"],"default":null}
    ]
}
`

var HttpSourceLogStr = `
{
	"accountId": null,
	"accountName": null,
	"accountProofId": null,
	"apiId": null,
	"apiName": null,
	"apiTags": [],
	"cloudTs": {
		"long": 1730122097
	},
	"customer": "10001001",
	"devUId": null,
	"deviceId": "",
	"deviceIp": {
		"string": ""
	},
	"dstAssetId": {
		"string": "0"
	},
	"dstCity": "",
	"dstCountry": "局域网",
	"dstIp": "200.200.0.63",
	"dstIpTag": 0,
	"dstMac": "",
	"dstPort": 80,
	"dstProvince": "局域网",
	"dstRegionId": {
		"string": "671f347d90dd2f6082f010c0"
	},
	"dstSubType": 0,
	"dstType": 3,
	"duration": 2,
	"encPayloadType": null,
	"encReqType": null,
	"encRspType": null,
	"encryptType": null,
	"extensions": {
		"string": "{\"xSrcIp\":\"192.168.2.0\"}"
	},
	"greDstIp": [],
	"greSrcIp": [],
	"host": null,
	"hostIp": "",
	"hostIpValid": "",
	"httpId": "742876546",
	"insertTimestamp": 1730122618,
	"logSampled": {
		"int": 0
	},
	"logTraceInfo": {
		"string": "{\"appName\":\"logDetect\",\"timestamp\":1730122097}|{\"appName\":\"logUpload\",\"timestamp\":1730122618}|{\"appName\":\"collect\",\"timestamp\":1730122618}|{\"appName\":\"transfer\",\"timestamp\":1730122619,\"uuId\":\"http_log-1730122097-r9Qi3\"}"
	},
	"logType": "",
	"manage": "",
	"manageIp": {
		"string": ""
	},
	"moduleType": "",
	"mplsLabel": [],
	"originProductType": "STA",
	"originProductVer": "STA3.0.39",
	"productType": "STA",
	"productVer": "STA3.0.39",
	"rawMsg": null,
	"recordTime": "2024-10-28 21:28:17 ",
	"recordTimestamp": 1732204801,
	"reqBodyLen": {
		"int": -1
	},
	"reqContentType": "application/json",
	"reqDataClassifications": [],
	"reqDataCounts": [],
	"reqDataGrade": null,
	"reqDataLabelIds": [],
	"reqDataValues": null,
	"reqMethod": "POST",
	"requestBody": "{\"name\":\"xiaoqiang\",\"password\":\"13875412148\",\"phone\":\"13875412148\"}",
	"requestHead": "POST /api/MarketingStatus/UpdateStatus HTTP/1.1\r\nHost: sangfor.poc.com \r\nAccept: */*\r\nContent-Type: application/json\r\nContent-Length: 230\r\n\r\n",
	"respBodyLen": {
		"int": -1
	},
	"respContentType": "application/json",
	"respDataClassifications": [],
	"respDataCounts": [],
	"respDataGrade": null,
	"respDataLabelIds": [],
	"respDataValues": null,
	"respServer": "",
	"respStatus": 200,
	"responseBody": "[{\"key\":\"idCard_7\",\"value\":\"140829199204081921\"},{\"key\":\"idCard_8\",\"value\":\"513430193710240938\"},{\"key\":\"email_0\",\"value\":\"vgao@example.net\"},{\"key\":\"companyName_1\",\"value\":\"XYZ有限公司\"},{\"key\":\"username_1\",\"value\":\"王梅\"},{\"key\":\"username_3\",\"value\":\"萧想\"},{\"key\":\"email_5\",\"value\":\"qdai@example.com\"},{\"key\":\"username_2\",\"value\":\"牛伟\"},{\"key\":\"username_4\",\"value\":\"李鹏\"},{\"key\":\"username_9\",\"value\":\"黄丽丽\"},{\"key\":\"email_6\",\"value\":\"qiangcheng@example.net\"},{\"key\":\"phone_card_1\",\"value\":\"021-23456789\"},{\"key\":\"phone_card_4\",\"value\":\"028-56789012\"},{\"key\":\"phone_card_7\",\"value\":\"028-56789015\"},{\"key\":\"phone_card_5\",\"value\":\"028-56789013\"},{\"key\":\"companyName_2\",\"value\":\"123科技有限责任公司\"},{\"key\":\"companyName_3\",\"value\":\"橙子网络科技股份有限公司\"},{\"key\":\"companyName_7\",\"value\":\"绿叶食品集团有限公司3\"},{\"key\":\"email_2\",\"value\":\"jing89@example.org\"},{\"key\":\"email_4\",\"value\":\"rluo@example.com\"},{\"key\":\"email_9\",\"value\":\"yuanlei@example.org\"},{\"key\":\"phone_card_0\",\"value\":\"010-12345678\"},{\"key\":\"idCard_9\",\"value\":\"420503198710218401\"},{\"key\":\"username_0\",\"value\":\"王杰\"},{\"key\":\"username_8\",\"value\":\"何鹏\"},{\"key\":\"idCard_0\",\"value\":\"210283195711274627\"},{\"key\":\"idCard_3\",\"value\":\"140827198512022977\"},{\"key\":\"email_1\",\"value\":\"oyan@example.net\"},{\"key\":\"email_7\",\"value\":\"gaoxia@example.net\"},{\"key\":\"phone_card_6\",\"value\":\"028-56789014\"},{\"key\":\"companyName_0\",\"value\":\"ABC公司\"},{\"key\":\"username_5\",\"value\":\"邹秀荣\"},{\"key\":\"username_7\",\"value\":\"宫俊\"},{\"key\":\"idCard_1\",\"value\":\"130827195009114940\"},{\"key\":\"idCard_4\",\"value\":\"330602197501144840\"},{\"key\":\"idCard_5\",\"value\":\"441226196607162431\"},{\"key\":\"idCard_6\",\"value\":\"130723194812145783\"},{\"key\":\"email_8\",\"value\":\"fliao@example.com\"},{\"key\":\"phone_card_2\",\"value\":\"020-34567890\"},{\"key\":\"phone_card_3\",\"value\":\"0755-45678901\"},{\"key\":\"idCard_2\",\"value\":\"13102819641006540X\"},{\"key\":\"username_6\",\"value\":\"韩超\"},{\"key\":\"email_3\",\"value\":\"yinfang@example.com\"},{\"key\":\"companyName_4\",\"value\":\"绿叶食品集团有限公司\"},{\"key\":\"companyName_5\",\"value\":\"绿叶食品集团有限公司1\"},{\"key\":\"companyName_6\",\"value\":\"绿叶食品集团有限公司2\"}]",
	"responseHead": "HTTP/1.1 200 OK\r\nCache-Control: private\r\nContent-Length: 32\r\nContent-Type: application/json; charset=utf-8\r\nServer: Microsoft-IIS/7.5\r\nX-AspNet-Version: 4.0.30319\r\nX-Powered-By: ASP.NET\r\nDate: Mon, 21 Oct 2024 16:00:00 GMT\r\n\r\n",
	"sessionId": "d0750500-7f70-48a6-9362-5b70884d96c5",
	"srcAssetId": {
		"string": "0"
	},
	"srcCity": "深圳市",
	"srcCountry": "Brazil",
	"srcIp": "200.200.1.1",
	"srcIpTag": 0,
	"srcMac": "",
	"srcPort": 40392,
	"srcProvince": "广东",
	"srcRegionId": {
		"string": "000000000000000000000000"
	},
	"srcSubType": 0,
	"srcType": 0,
	"tenant": "10001001",
	"tunnelProtocol": [],
	"uploadTime": "2024-10-28 21:36:58 ",
	"uploadTimestamp": 1730122618,
	"uri": "/api/MarketingStatus/UpdateStatus",
	"url": "/api/MarketingStatus/UpdateStatus",
	"urlHash": null,
	"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
	"uuId": "3b14bdf6-9c19-40d4-8dc1-3e64a0d171cc",
	"v": 1,
	"vendor": "sangfor",
	"vlanId": [],
	"vxlanId": [],
	"xAppGroup": null,
	"xAppId": null,
	"xAppName": null,
	"xAppTags": [],
	"xForwardedFor": "",
	"xForwardedForTag": {
		"int": -1
	},
	"xUserDomain": null,
	"xUserGroup": null,
	"xUserGroupId": null,
	"xUserId": null,
	"xUserName": null,
	"xUserProofId": null,
	"xUserRoles": [],
	"xUserSource": null,
	"xUserTags": []
}`
