// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: req.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 修改阈值的请求
type ModifyRiskThresholdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 数据安全大脑的IP
	DscIp string `protobuf:"bytes,1,opt,name=dsc_ip,json=dscIp,proto3" json:"dsc_ip,omitempty"`
	// 数据安全大脑的前端账号
	DscFeAccount string `protobuf:"bytes,2,opt,name=dsc_fe_account,json=dscFeAccount,proto3" json:"dsc_fe_account,omitempty"`
	// 数据安全大脑的前端账号
	DscFePassword string `protobuf:"bytes,3,opt,name=dsc_fe_password,json=dscFePassword,proto3" json:"dsc_fe_password,omitempty"`
	// 模式,是poc还是default
	ModifyMode string `protobuf:"bytes,4,opt,name=modify_mode,json=modifyMode,proto3" json:"modify_mode,omitempty"`
}

func (x *ModifyRiskThresholdRequest) Reset() {
	*x = ModifyRiskThresholdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyRiskThresholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyRiskThresholdRequest) ProtoMessage() {}

func (x *ModifyRiskThresholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_req_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyRiskThresholdRequest.ProtoReflect.Descriptor instead.
func (*ModifyRiskThresholdRequest) Descriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{0}
}

func (x *ModifyRiskThresholdRequest) GetDscIp() string {
	if x != nil {
		return x.DscIp
	}
	return ""
}

func (x *ModifyRiskThresholdRequest) GetDscFeAccount() string {
	if x != nil {
		return x.DscFeAccount
	}
	return ""
}

func (x *ModifyRiskThresholdRequest) GetDscFePassword() string {
	if x != nil {
		return x.DscFePassword
	}
	return ""
}

func (x *ModifyRiskThresholdRequest) GetModifyMode() string {
	if x != nil {
		return x.ModifyMode
	}
	return ""
}

// 修改阈值的响应
type ModifyRiskThresholdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Meta string `protobuf:"bytes,2,opt,name=Meta,proto3" json:"Meta,omitempty"`
}

func (x *ModifyRiskThresholdResponse) Reset() {
	*x = ModifyRiskThresholdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyRiskThresholdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyRiskThresholdResponse) ProtoMessage() {}

func (x *ModifyRiskThresholdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_req_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyRiskThresholdResponse.ProtoReflect.Descriptor instead.
func (*ModifyRiskThresholdResponse) Descriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{1}
}

func (x *ModifyRiskThresholdResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ModifyRiskThresholdResponse) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

var File_req_proto protoreflect.FileDescriptor

var file_req_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x1a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x69, 0x73,
	0x6b, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x73, 0x63, 0x5f, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x64, 0x73, 0x63, 0x49, 0x70, 0x12, 0x24, 0x0a, 0x0e, 0x64, 0x73, 0x63, 0x5f,
	0x66, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x64, 0x73, 0x63, 0x46, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26,
	0x0a, 0x0f, 0x64, 0x73, 0x63, 0x5f, 0x66, 0x65, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x73, 0x63, 0x46, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64,
	0x69, 0x66, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x45, 0x0a, 0x1b, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x52, 0x69, 0x73, 0x6b, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x65,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x32, 0x6c,
	0x0a, 0x0a, 0x44, 0x53, 0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x13,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x69, 0x73, 0x6b, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68,
	0x6f, 0x6c, 0x64, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x52, 0x69, 0x73, 0x6b, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x69, 0x73, 0x6b, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f,
	0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_req_proto_rawDescOnce sync.Once
	file_req_proto_rawDescData = file_req_proto_rawDesc
)

func file_req_proto_rawDescGZIP() []byte {
	file_req_proto_rawDescOnce.Do(func() {
		file_req_proto_rawDescData = protoimpl.X.CompressGZIP(file_req_proto_rawDescData)
	})
	return file_req_proto_rawDescData
}

var file_req_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_req_proto_goTypes = []interface{}{
	(*ModifyRiskThresholdRequest)(nil),  // 0: proto.ModifyRiskThresholdRequest
	(*ModifyRiskThresholdResponse)(nil), // 1: proto.ModifyRiskThresholdResponse
}
var file_req_proto_depIdxs = []int32{
	0, // 0: proto.DSCService.ModifyRiskThreshold:input_type -> proto.ModifyRiskThresholdRequest
	1, // 1: proto.DSCService.ModifyRiskThreshold:output_type -> proto.ModifyRiskThresholdResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_req_proto_init() }
func file_req_proto_init() {
	if File_req_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_req_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyRiskThresholdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_req_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyRiskThresholdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_req_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_req_proto_goTypes,
		DependencyIndexes: file_req_proto_depIdxs,
		MessageInfos:      file_req_proto_msgTypes,
	}.Build()
	File_req_proto = out.File
	file_req_proto_rawDesc = nil
	file_req_proto_goTypes = nil
	file_req_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DSCServiceClient is the client API for DSCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DSCServiceClient interface {
	ModifyRiskThreshold(ctx context.Context, in *ModifyRiskThresholdRequest, opts ...grpc.CallOption) (*ModifyRiskThresholdResponse, error)
}

type dSCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDSCServiceClient(cc grpc.ClientConnInterface) DSCServiceClient {
	return &dSCServiceClient{cc}
}

func (c *dSCServiceClient) ModifyRiskThreshold(ctx context.Context, in *ModifyRiskThresholdRequest, opts ...grpc.CallOption) (*ModifyRiskThresholdResponse, error) {
	out := new(ModifyRiskThresholdResponse)
	err := c.cc.Invoke(ctx, "/proto.DSCService/ModifyRiskThreshold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DSCServiceServer is the server API for DSCService service.
type DSCServiceServer interface {
	ModifyRiskThreshold(context.Context, *ModifyRiskThresholdRequest) (*ModifyRiskThresholdResponse, error)
}

// UnimplementedDSCServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDSCServiceServer struct {
}

func (*UnimplementedDSCServiceServer) ModifyRiskThreshold(context.Context, *ModifyRiskThresholdRequest) (*ModifyRiskThresholdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyRiskThreshold not implemented")
}

func RegisterDSCServiceServer(s *grpc.Server, srv DSCServiceServer) {
	s.RegisterService(&_DSCService_serviceDesc, srv)
}

func _DSCService_ModifyRiskThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyRiskThresholdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCServiceServer).ModifyRiskThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DSCService/ModifyRiskThreshold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCServiceServer).ModifyRiskThreshold(ctx, req.(*ModifyRiskThresholdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DSCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DSCService",
	HandlerType: (*DSCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModifyRiskThreshold",
			Handler:    _DSCService_ModifyRiskThreshold_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "req.proto",
}
