// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: req.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DSCService_ModifyRiskThreshold_FullMethodName = "/proto.DSCService/ModifyRiskThreshold"
)

// DSCServiceClient is the client API for DSCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DSCServiceClient interface {
	ModifyRiskThreshold(ctx context.Context, in *ModifyRiskThresholdRequest, opts ...grpc.CallOption) (*ModifyRiskThresholdResponse, error)
}

type dSCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDSCServiceClient(cc grpc.ClientConnInterface) DSCServiceClient {
	return &dSCServiceClient{cc}
}

func (c *dSCServiceClient) ModifyRiskThreshold(ctx context.Context, in *ModifyRiskThresholdRequest, opts ...grpc.CallOption) (*ModifyRiskThresholdResponse, error) {
	out := new(ModifyRiskThresholdResponse)
	err := c.cc.Invoke(ctx, DSCService_ModifyRiskThreshold_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DSCServiceServer is the server API for DSCService service.
// All implementations must embed UnimplementedDSCServiceServer
// for forward compatibility
type DSCServiceServer interface {
	ModifyRiskThreshold(context.Context, *ModifyRiskThresholdRequest) (*ModifyRiskThresholdResponse, error)
	mustEmbedUnimplementedDSCServiceServer()
}

// UnimplementedDSCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDSCServiceServer struct {
}

func (UnimplementedDSCServiceServer) ModifyRiskThreshold(context.Context, *ModifyRiskThresholdRequest) (*ModifyRiskThresholdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyRiskThreshold not implemented")
}
func (UnimplementedDSCServiceServer) mustEmbedUnimplementedDSCServiceServer() {}

// UnsafeDSCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DSCServiceServer will
// result in compilation errors.
type UnsafeDSCServiceServer interface {
	mustEmbedUnimplementedDSCServiceServer()
}

func RegisterDSCServiceServer(s grpc.ServiceRegistrar, srv DSCServiceServer) {
	s.RegisterService(&DSCService_ServiceDesc, srv)
}

func _DSCService_ModifyRiskThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyRiskThresholdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSCServiceServer).ModifyRiskThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DSCService_ModifyRiskThreshold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSCServiceServer).ModifyRiskThreshold(ctx, req.(*ModifyRiskThresholdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DSCService_ServiceDesc is the grpc.ServiceDesc for DSCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DSCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DSCService",
	HandlerType: (*DSCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModifyRiskThreshold",
			Handler:    _DSCService_ModifyRiskThreshold_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "req.proto",
}
