import Vue from 'vue'
import {
  Message,
  Form,
  FormItem,
  Input,
  Button,
  ButtonGroup,
  Container,
  Aside,
  Main,
  Header,
  RadioButton,
  Menu,
  Submenu,
  MenuItemGroup,
  MenuItem,
  RadioGroup,
  Breadcrumb,
  BreadcrumbItem,
  Card,
  Row,
  Col,
  Table,
  TableColumn,
  Switch,
  Tooltip,
  Pagination,
  Timeline,
  TimelineItem,
  Backtop,
  Avatar,
  Dialog,
  MessageBox,
  Tag,
  Image,
  Divider,
  Rate,
  Alert,
  Step,
  Steps,
  Select,
  Option,
  Tabs,
  TabPane,
  Upload
} from 'element-ui'

Vue.prototype.$message = Message
Vue.use(RadioGroup)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Button)
Vue.use(ButtonGroup)
Vue.use(Container)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Header)
Vue.use(RadioButton)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(RadioGroup)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Col)
Vue.use(Row)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Timeline)
Vue.use(TimelineItem)
Vue.use(Backtop)
Vue.use(Avatar)
Vue.use(Dialog)
Vue.use(Tag)
Vue.use(Image)
Vue.use(Divider)
Vue.use(Rate)
Vue.use(Alert)
Vue.use(Step)
Vue.use(Steps)
Vue.use(Select)
Vue.use(Option)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Upload)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
