# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addDataClassify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61\x64\x64\x44\x61taClassify.proto\x12\x05proto\"p\n\x16\x41\x64\x64\x44\x61taClassifyRequest\x12\x0e\n\x06\x64sc_ip\x18\x01 \x01(\t\x12\x16\n\x0e\x64sc_fe_account\x18\x02 \x01(\t\x12\x17\n\x0f\x64sc_fe_password\x18\x03 \x01(\t\x12\x15\n\rpostgreSQL_ip\x18\x04 \x01(\t\"5\n\x17\x41\x64\x64\x44\x61taClassifyResponse\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\x12\x0c\n\x04Meta\x18\x02 \x01(\t2l\n\x16\x41\x64\x64\x44\x61taClassifyService\x12R\n\x0f\x41\x64\x64\x44\x61taClassify\x12\x1d.proto.AddDataClassifyRequest\x1a\x1e.proto.AddDataClassifyResponse\"\x00\x42\tZ\x07.;protob\x06proto3')



_ADDDATACLASSIFYREQUEST = DESCRIPTOR.message_types_by_name['AddDataClassifyRequest']
_ADDDATACLASSIFYRESPONSE = DESCRIPTOR.message_types_by_name['AddDataClassifyResponse']
AddDataClassifyRequest = _reflection.GeneratedProtocolMessageType('AddDataClassifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDDATACLASSIFYREQUEST,
  '__module__' : 'addDataClassify_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddDataClassifyRequest)
  })
_sym_db.RegisterMessage(AddDataClassifyRequest)

AddDataClassifyResponse = _reflection.GeneratedProtocolMessageType('AddDataClassifyResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDDATACLASSIFYRESPONSE,
  '__module__' : 'addDataClassify_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddDataClassifyResponse)
  })
_sym_db.RegisterMessage(AddDataClassifyResponse)

_ADDDATACLASSIFYSERVICE = DESCRIPTOR.services_by_name['AddDataClassifyService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007.;proto'
  _ADDDATACLASSIFYREQUEST._serialized_start=32
  _ADDDATACLASSIFYREQUEST._serialized_end=144
  _ADDDATACLASSIFYRESPONSE._serialized_start=146
  _ADDDATACLASSIFYRESPONSE._serialized_end=199
  _ADDDATACLASSIFYSERVICE._serialized_start=201
  _ADDDATACLASSIFYSERVICE._serialized_end=309
# @@protoc_insertion_point(module_scope)
