# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import req_pb2 as req__pb2


class DSCServiceStub(object):
    """面向DSC的grpc服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ModifyRiskThreshold = channel.unary_unary(
            '/proto.DSCService/ModifyRiskThreshold',
            request_serializer=req__pb2.ModifyRiskThresholdRequest.SerializeToString,
            response_deserializer=req__pb2.ModifyRiskThresholdResponse.FromString,
        )


class DSCServiceServicer(object):
    """面向DSC的grpc服务
    """

    def ModifyRiskThreshold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DSCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ModifyRiskThreshold': grpc.unary_unary_rpc_method_handler(
            servicer.ModifyRiskThreshold,
            request_deserializer=req__pb2.ModifyRiskThresholdRequest.FromString,
            response_serializer=req__pb2.ModifyRiskThresholdResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'proto.DSCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class DSCService(object):
    """面向DSC的grpc服务
    """

    @staticmethod
    def ModifyRiskThreshold(request,
                            target,
                            options=(),
                            channel_credentials=None,
                            call_credentials=None,
                            insecure=False,
                            compression=None,
                            wait_for_ready=None,
                            timeout=None,
                            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.DSCService/ModifyRiskThreshold',
                                             req__pb2.ModifyRiskThresholdRequest.SerializeToString,
                                             req__pb2.ModifyRiskThresholdResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
