# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: req.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\treq.proto\x12\x05proto\"r\n\x1aModifyRiskThresholdRequest\x12\x0e\n\x06\x64sc_ip\x18\x01 \x01(\t\x12\x16\n\x0e\x64sc_fe_account\x18\x02 \x01(\t\x12\x17\n\x0f\x64sc_fe_password\x18\x03 \x01(\t\x12\x13\n\x0bmodify_mode\x18\x04 \x01(\t\"9\n\x1bModifyRiskThresholdResponse\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\x12\x0c\n\x04Meta\x18\x02 \x01(\t2l\n\nDSCService\x12^\n\x13ModifyRiskThreshold\x12!.proto.ModifyRiskThresholdRequest\x1a\".proto.ModifyRiskThresholdResponse\"\x00\x42\tZ\x07.;protob\x06proto3')



_MODIFYRISKTHRESHOLDREQUEST = DESCRIPTOR.message_types_by_name['ModifyRiskThresholdRequest']
_MODIFYRISKTHRESHOLDRESPONSE = DESCRIPTOR.message_types_by_name['ModifyRiskThresholdResponse']
ModifyRiskThresholdRequest = _reflection.GeneratedProtocolMessageType('ModifyRiskThresholdRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODIFYRISKTHRESHOLDREQUEST,
  '__module__' : 'req_pb2'
  # @@protoc_insertion_point(class_scope:proto.ModifyRiskThresholdRequest)
  })
_sym_db.RegisterMessage(ModifyRiskThresholdRequest)

ModifyRiskThresholdResponse = _reflection.GeneratedProtocolMessageType('ModifyRiskThresholdResponse', (_message.Message,), {
  'DESCRIPTOR' : _MODIFYRISKTHRESHOLDRESPONSE,
  '__module__' : 'req_pb2'
  # @@protoc_insertion_point(class_scope:proto.ModifyRiskThresholdResponse)
  })
_sym_db.RegisterMessage(ModifyRiskThresholdResponse)

_DSCSERVICE = DESCRIPTOR.services_by_name['DSCService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007.;proto'
  _MODIFYRISKTHRESHOLDREQUEST._serialized_start=20
  _MODIFYRISKTHRESHOLDREQUEST._serialized_end=134
  _MODIFYRISKTHRESHOLDRESPONSE._serialized_start=136
  _MODIFYRISKTHRESHOLDRESPONSE._serialized_end=193
  _DSCSERVICE._serialized_start=195
  _DSCSERVICE._serialized_end=303
# @@protoc_insertion_point(module_scope)
